"use strict"
/* A lot of questions have nearly identical marking criteria here, and each pair of English-French can be used to generate two questions. It is therefore easier and more compact to procedurally generate the question list from a list of vocabulary pairs. */
var resources_gcse_french = {
	vocab: [
		["welcome","l'accueil"],
		["reception","l'accueil"],
		["teenager","l'adolescent"],
		["teenager","l'adolescente"],
		["to adore","adorer"],
		["to love","adorer"],
		["adult","l'adulte"],
		["to help","aider"],
		["to like","aimer"],
		["to love","aimer"],
		["friend","l'ami"],
		["friend","l'amie"],
		["friendship","l'amitié"],
		["love","l'amour"],
		["great-grandmother","l'arrière-grand-mère"],
		["great-grandfather","l'arrière-grand-père"],
		["great-grandparents","les arrière-grand-parents"],
		["opinion","l'avis"],
		["in my opinion","à mon avis"],
		["to be allowed to","avoir la permission de"],
		["to be right","avoir raison"],
		["to be wrong","avoir tort"],
		["group","la bande"],
		["group of friends","la bande d'amis"],
		["stepchildren","les beaux-enfants"],
		["stepson","le beau-fils"],
		["son-in-law","le beau-fils"],
		["brother-in-law","le beau-frère"],
		["stepfather","le beau-père"],
		["father-in-law","le beau-père"],
		["baby","le bébé"],
		["daughter-in-law","la belle-fille"],
		["stepdaughter","la belle-fille"],
		["mother-in-law","la belle-mère"],
		["stepmother","la belle-mère"],
		["sister-in-law","la belle-sœur"],
		["friend","le camarade"],
		["mate","le camarade"],
		["classmate","le camarade"],
		["companion","le camarade"],
		["friend","la camarade"],
		["mate","la camarade"],
		["classmate","la camarade"],
		["companion","la camarade"],
		["friendship","la camaraderie"],
		["fellowship","la camaraderie"],
		["dear","cher"],
		["dear","chère"],
		["darling","chéri"],
		["circle","le cercle"],
		["to understand","comprendre"],
		["acquaintance","la connaissance"],
		["relationship","la connaissance"],
		["known","connu"],
		["acquainted","connu"],
		["couple","le couple"],
		["friend","le copain"],
		["mate","le copain"],
		["buddy","le copain"],
		["friend","la copine"],
		["mate","la copine"],
		["cousin","le cousin"],
		["cousin","la cousine"],
		["agreed","d'accord"],
		["half-brother","le demi-frère"],
		["half-sister","la demi-sœur"],
		["to hate","détester"],
		["to discuss","discuter"],
		["divorced","divorcé"],
		["child","l'enfant"],
		["to marry","épouser"],
		["spouse","l'époux"],
		["spouse","l'épouse"],
		["to be friend with","être ami avec"],
		["related to","être parent"],
		["to get to know","faire la connaissance de"],
		["meet","faire la connaissance de"],
		["family","la famille"],
		["woman","la femme"],
		["wife","la femme"],
		["engaged","fiancé"],
		["fiancé","le fiancé"],
		["fiancée","la fiancée"],
		["young girl","la fillette"],
		["godson","le filleul"],
		["god-daughter","la filleule"],
		["only child","le fils unique"],
		["only child","la fille unique"],
		["brother","frère"],
		["son-in-law","le gendre"],
		["grandmother","la grand-mère"],
		["grandparents","les grands-parents"],
		["grandfather","le grand-père"],
		["man","l'homme"],
		["to forbid","interdire"],
		["young woman","la jeune femme"],
		["young teenage girl","la jeune fille"],
		["young man","le jeune homme"],
		["twins","les jumeaux"],
		["twins","les jumelles"],
		["relationship","les liens"],
		["Madam","Madame"],
		["Mrs","Madame"],
		["Miss","Mademoiselle"],
		["marriage","le mariage"],
		["married","marié"],
		["godmother","la marraine"],
		["mother","la mère"],
		["mum","la mère"],
		["Sir","Monsieur"],
		["Mr","Monsieur"],
		["nephew","le neveu"],
		["niece","la nièce"],
		["surname","le nom de famille"],
		["maiden name","le nom de jeune fille"],
		["uncle","l'oncle"],
		["godfather","le parrain"],
		["relative","le parent"],
		["relation","le parent"],
		["related to","parent de"],
		["related to","parente de"],
		["parents","les parents"],
		["unfair","pas juste"],
		["father","le père"],
		["to allow","permettre"],
		["permission","la permission"],
		["grandchildren","les petits-enfants"],
		["grandchildren","les petites-enfants"],
		["grandson","le petit-fils"],
		["granddaughter","la petite-fille"],
		["first name","le prénom"],
		["close","proche"],
		["relationship","le rapport"],
		["relation","le rapport"],
		["separated","séparé"],
		["to get on with","s'entendre"],
		["to greet","saluer"],
		["to greet","accueillir"],
		["greeting","la salutation"],
		["to marry","se marier"],
		["sister","sœur"],
		["understanding","sympathique"],
		["pleasant","sympathique"],
		["likeable","sympathique"],
		["to want","vouloir"],
		["Buddhist","bouddhiste"],
		["Catholic","catholique"],
		["Christian","chrétien"],
		["Christian","chrétienne"],
		["Hindu","hindou"],
		["Islamic","islamique"],
		["Jew","juif"],
		["Jew","juive"],
		["Muslim","musulman"],
		["Muslim","musulmanne"],
		["Protestant","protestant"],
		["Protestant","protestante"],
		["Sikh","sikh"],
		["laundry","la buanderie"],
		["office","le bureau"],
		["cellar","la cave"],
		["corridor","le couloir"],
		["bedroom","la chambre"],
		["kitchen","la cuisine"],
		["entrance","l'entrée"],
		["driveway","l'entrée de garage"],
		["stairs","l'escalier"],
		["garage","le garage"],
		["attic","le grenier"],
		["garden","le jardin"],
		["dining room","la salle à manger"],
		["shower room","la salle d'eau"],
		["wet room","la salle d'eau"],
		["bathroom","la salle de bains"],
		["en suite bathroom","la salle de bains individuelle"],
		["living room","la salle de séjour"],
		["lounge","le salon"],
		["terrace","la terrasse"],
		["patio","la terrasse"],
		["toilets","les WCs"],
		["toilets","les toilettes"],
		["fashionable","à la mode"],
		["to fit","aller bien"],
		["to suit","aller bien"],
		["money","l'argent"],
		["silver","l'argent"],
		["silvery","argenté"],
		["ring","la bague"],
		["trainers","les baskets"],
		["beige","beige"],
		["jewellery","les bijoux"],
		["note","le billet"],
		["white","blanc"],
		["blue","bleu"],
		["navy blue","bleu marine"],
		["blouse","la blouse"],
		["cheap","bon marché"],
		["beanie","le bonnet"],
		["woolly hat","le bonnet"],
		["boot","la botte"],
		["earring","la boucle d'oreille"],
		["fashion shop","la boutique"],
		["boutique","la boutique"],
		["bracelet","le bracelet"],
		["hood","la capuche"],
		["checked","à carreaux"],
		["cap","la casquette"],
		["belt","la ceinture"],
		["sweater","le chandail"],
		["pullover","le chandail"],
		["hat","le chapeau"],
		["sock","la chaussette"],
		["slipper","le chausson"],
		["shoe","la chaussure"],
		["high heel shoe","la chaussure à talons hauts"],
		["shirt","la chemise"],
		["blouse","le chemisier"],
		["expensive","cher"],
		["expensive","chère"],
		["stylish","chic"],
		["chic","chic"],
		["light","clair"],
		["classic","classique"],
		["tights","le collant"],
		["necklace","le collier"],
		["suit","le complet"],
		["conventional","conventionnel"],
		["tie","la cravate"],
		["golden","doré"],
		["scarf","l'écharpe"],
		["to try on","essayer"],
		["dark","foncé"],
		["scarf","le foulard"],
		["glove","le gant"],
		["big","grand"],
		["grey","gris"],
		["rain coat","l'imperméable"],
		["yellow","jaune"],
		["skirt","la jupe"],
		["swimming suit","le maillot de bain"],
		["swimming trunks","le maillot de bain"],
		["bathing costume","le maillot de bain"],
		["coat","le manteau"],
		["make-up","le maquillage"],
		["brown","marron"],
		["fashion","la mode"],
		["watch","la montre"],
		["multicoloured","multicolore"],
		["black","noir"],
		["gold","l'or"],
		["orange","orange"],
		["trousers","le pantalon"],
		["to pay","payer"],
		["small","petit"],
		["short","petit"],
		["coin","la pièce"],
		["pocket","la poche"],
		["spotty","à pois"],
		["with dots","à pois"],
		["to wear","porter"],
		["pullover","le pull"],
		["pyjamas","le pyjama"],
		["striped","à rayures"],
		["dress","la robe"],
		["dressing gown","la robe de chambre"],
		["pink","rose"],
		["red","rouge"],
		["lipstick","le rouge à lèvres"],
		["suit","le tailleur"],
		["turquoise","turquoise"],
		["handbag","le sac à main"],
		["bag","le sac"],
		["changing room","la salle d'essayage"],
		["sandal","la sandale"],
		["narrow","serré"],
		["tight","serré"],
		["shorts","le short"],
		["tracksuit","le survêtement"],
		["hoodie","le sweat à capuche"],
		["size","taille"],
		["T-shirt","le tee-shirt"],
		["plain","uni"],
		["green","vert"],
		["jacket","la veste"],
		["clothing","les vêtements"],
		["purple","violet"],
		["violet","violet"],
		["at","arrobas"],
		["to abort","abandonner"],
		["access","l'accès"],
		["to enlarge","agrandir"],
		["to switch on","allumer"],
		["to cancel","annuler"],
		["digital camera","l'appareil-photo numérique"],
		["application","l'application"],
		["app","l'appli"],
		["to apply","appliquer"],
		["to hit the key","appuyer sur la touche"],
		["to hit the key","taper sur la touche"],
		["to attach","attacher"],
		["database","la base de données"],
		["space bar","la barre d'espacement"],
		["browser bar","la barre du navigateur"],
		["to charge","charger"],
		["chat","chatter"],
		["to chat online","clavarder"],
		["keyboard","le clavier"],
		["to click","cliquer"],
		["command","la commande"],
		["Internet connection","la connexion sur Internet"],
		["to copy","copier"],
		["to copy and paste","copier-coller"],
		["to cut","couper"],
		["to cut and paste","couper-coller"],
		["e-mail","le courrier électronique"],
		["junk mail","le courrier indésirable"],
		["to create","créer"],
		["cursor","le curseur"],
		["to move","déplacer"],
		["to drag","déplacer"],
		["document","le document"],
		["double click","double cliquer"],
		["headphones","les écouteurs"],
		["screen","l'écran"],
		["to edit","éditer"],
		["to edit texts","éditer des textes"],
		["to edit photos","éditer des photos"],
		["to delete","effacer"],
		["to remove","enlever"],
		["to save","enregistrer"],
		["to enter","entrer"],
		["to send text messages","envoyer des textos"],
		["to switch off","éteindre"],
		["to drag","faire glisser"],
		["window","la fenêtre"],
		["file","le fichier"],
		["arrow key","la flèche"],
		["to attach","joindre"],
		["to drag and drop","glisser-déposer"],
		["to drag and move","glisser-déplacer"],
		["to burn a CD","graver un cd"],
		["icon","l'icône"],
		["printer","l'imprimante"],
		["to print out","imprimer"],
		["ICT","l'informatique"],
		["insérer","to insert"],
		["internet","l'internet"],
		["iPad","l'iPad"],
		["iPhone","l'iPhone"],
		["iPod","l'iPod"],
		["computer game","le jeu électronique"],
		["video game","le jeu vidéo"],
		["link","le lien"],
		["software","le logiciel"],
		["antivirus software","le logiciel antivirus"],
		["hardware","le matériel informatique"],
		["menu","le menu"],
		["text messaging","le messagerie"],
		["password","le mot de passe"],
		["search engine","le moteur de recherche"],
		["browser","le navigateur"],
		["to browse","naviguer"],
		["option","l'option"]
	],
	processedVocab:{E2F:{},F2E:{}},
	/* longer tasks which require regular question constructors */
	misc: [
	],
	diacritics:"âàçéêèëîìïôòœûùü".split(""),
	generateQuestionList: function() {
		let out = []
		for (let i of Object.keys(this.processedVocab.E2F)) {
			let maxMark = resources_gcse_french.processedVocab.E2F[i].map(x=>x.split(/[ |\'|-]/g).length).reduce((x,y)=>Math.min(x,y))
			// wouldn't want it to be too easy to guess the number of words :D
			maxMark = Math.max(Math.round(maxMark*Math.exp(0.2*Math.random()-1)+Math.random()-0.5),1)
			let diacritics = false // if diacritics are in the answer, show a message with copy-pastable symbols and add extra time
			diacriticFor: for (let j of resources_gcse_french.diacritics) for (let k of resources_gcse_french.processedVocab.E2F[i]) if (k.includes(j)) {
				diacritics = true
				break diacriticFor
			}
			let markString = "123456789".repeat(Math.ceil(maxMark/9)).split("").map(x=>Number(x)).sort((a,b)=>(a**(diacritics?(1/3):0.5))*Math.random()-(b**(diacritics?(1/3):0.5))*Math.random()).join("")
			out.push({
				text:(diacritics?("<i>The answer to this question may include special characters: here they are to copy and paste.<br>"+resources_gcse_french.diacritics.join(" ")+"</i><br><br>"):"")+"Translate \""+i+"\" from English to French.",
				type:"open",
				modelAnswer:resources_gcse_french.processedVocab.E2F[i].join("; "),
				maxMark:maxMark,
				mark:function(answer){
					let out = 0
					for (let j of resources_gcse_french.processedVocab.E2F[i]) out = Math.max(out,keyword(answer,j.split(/[ |\'|-]/g))/j.split(/[ |\'|-]/g).length)
					return markString.slice(0,maxMark*out)
				},
				par:maxMark*(diacritics?4:3)+(diacritics?11:7)
			})
			if (resources_gcse_french.processedVocab.E2F[i].length>3) out.push({
				text:"Which "+numword(resources_gcse_french.processedVocab.E2F[i].length)+" of the below can mean \""+i+"\" in French?",
				type:"multiplechoice",
				answers:multipleChoiceGenerator(resources_gcse_french.processedVocab.E2F[i],resources_gcse_french.processedVocab.E2F[i].length,Object.keys(resources_gcse_french.processedVocab.E2F).select(10).map(j=>resources_gcse_french.processedVocab.E2F[j]).flat(),resources_gcse_french.processedVocab.E2F[i].length),
				markTransform:x=>"1234".repeat(Math.ceil(x/4)).slice(0,x),
				par:10+5*resources_gcse_french.processedVocab.E2F[i].length
			})
		}
		for (let i of Object.keys(this.processedVocab.F2E)) {
			let maxMark = resources_gcse_french.processedVocab.F2E[i].map(x=>x.split(/[ |\'|-]/g).length).reduce((x,y)=>Math.min(x,y))
			let markString = "123456789".repeat(Math.ceil(maxMark/9)).split("").map(x=>Number(x)).sort((a,b)=>(a**0.25)*Math.random()-(b**0.25)*Math.random()).join("")
			out.push({
				text:"Translate \""+i+"\" from French to English.",
				type:"open",
				modelAnswer:resources_gcse_french.processedVocab.F2E[i].join("; "),
				maxMark:maxMark,
				mark:function(answer){
					let out = 0
					for (let j of resources_gcse_french.processedVocab.F2E[i]) out = Math.max(out,keyword(answer,j.split(/[ |\'|-]/g))/j.split(/[ |\'|-]/g).length)
					return markString.slice(0,maxMark*out)
				},
				par:maxMark*3+7
			})
			if (resources_gcse_french.processedVocab.F2E[i].length>3) out.push({
				text:"Which "+numword(resources_gcse_french.processedVocab.F2E[i].length)+" of the below can mean \""+i+"\" in English?",
				type:"multiplechoice",
				answers:multipleChoiceGenerator(resources_gcse_french.processedVocab.F2E[i],resources_gcse_french.processedVocab.F2E[i].length,Object.keys(resources_gcse_french.processedVocab.F2E).select(10).map(j=>resources_gcse_french.processedVocab.F2E[j]).flat(),resources_gcse_french.processedVocab.F2E[i].length),
				markTransform:x=>"1234".repeat(Math.ceil(x/4)).slice(0,x),
				par:10+5*resources_gcse_french.processedVocab.F2E[i].length
			})
		}
		return out
	}
}
for (let i of resources_gcse_french.vocab) {
	if (!(i[0] in resources_gcse_french.processedVocab.E2F)) {resources_gcse_french.processedVocab.E2F[i[0]] = []}
	resources_gcse_french.processedVocab.E2F[i[0]].push(i[1])
	if (!(i[1] in resources_gcse_french.processedVocab.F2E)) {resources_gcse_french.processedVocab.F2E[i[1]] = []}
	resources_gcse_french.processedVocab.F2E[i[1]].push(i[0])
}

var question_file_at_gcse_french = resources_gcse_french.generateQuestionList()